### PR TITLE
Avoid calling +[SEGAnalytics sharedAnalytics]

### LINKED ISSUE #17: Don't call +[SEGAnalytics sharedAnalytics]
We don't use the singleton instance `+[SEGAnalytics sharedAnalytics]` on our app: we create our own `SEGAnalytics` instance. We should be able to pass it as a parameter to this init:

https://github.com/BranchMetrics/Segment-Branch-iOS/blob/master/Pod/Classes/BNCBranchIntegration.m#L28

### PR DESCRIPTION
**Pull request by marcelofabri**
Fixes #17

### CODE REVIEW

**Comment by E-B-Smith** [comment]
Looks good.  What's some background for the change?

**Comment by E-B-Smith** [comment]
Oh great -- I see the referencing issue now.
👍

**Comment by marcelofabri** [comment]
Thanks for merging so quickly! Can we have a release with this change? 😊

**Comment by E-B-Smith** [comment]
Done.  The latest version is v0.1.17.

**Pull request merged**
